# https://github.com/github/issue-metrics/blob/main/docs/authenticating-with-github-app-installation.md
name: Monthly repo metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:

    - name: Get dates for last month
      shell: bash
      run: |
        # Calculate the first day of the previous month
        first_day=$(date -d "last month" +%Y-%m-01)

        # Calculate the last day of the previous month
        last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

        #Set an environment variable with the date range
        echo "$first_day..$last_day"
        echo "last_month=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v3
      env:
        GH_APP_ID: ${{ secrets.GH_APP_ID }}
        GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
        GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
        SEARCH_QUERY: 'repo:snickerjp/orabbix is:issue created:${{ env.last_month }} -reason:"not planned"'

#    - name: Get user names from team
#      run: |
#          teamMembers="$(gh api /orgs/ORG/teams/TEAM_SLUG/members | jq -r '.[].login' | paste -sd, -)"
#          echo 'TEAM_MEMBERS='$teamMembers >> $GITHUB_ENV
#        env:
#          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v5
      id: create_monthly_report_issue # Add id
      with:
        title: Monthly issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        labels: metrics # Corrected labels
        #assignees: ${{ env.TEAM_MEMBERS }}

    - name: Close monthly report issue # Add step to close issue
      uses: peter-evans/close-issue@v3
      with:
        repository: snickerjp/orabbix
        issue-number: ${{ steps.create_monthly_report_issue.outputs.issue-number }}
        comment: Automated report, closing.

    - name: Report on PRs
      uses: github/issue-metrics@v3
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:snickerjp/orabbix is:pr created:${{ env.last_month }} -is:draft'

    - name: Create report for PRs
      uses: peter-evans/create-issue-from-file@v5
      id: create_pr_report_issue # Add id
      with:
        title: Monthly PR metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        labels: metrics # Corrected labels

    - name: Close PR report issue # Add step to close issue
      uses: peter-evans/close-issue@v3
      with:
        repository: snickerjp/orabbix
        issue-number: ${{ steps.create_pr_report_issue.outputs.issue-number }}
        comment: Automated report, closing.
